### ISSUE TITLE
Using Azure Blob Storage as an event store for larger projects

### ISSUE THREAD

**Issue by dharmaturtle** [Lokad/AzureEventStore#13]
Hi! I'm thinking about using Azure Blob Storage as an event store for a large project. However, your [readme](https://github.com/Lokad/AzureEventStore/blob/master/README.md) indicates that this library is intended for small projects:

> You can use Lokad.AzureEventStore for your prototypes and small-scale projects, then move on to other solutions (such as Apache Kafka or Greg Young's Event Store) once you confirm the need for additional performance or features.

In particular:

> Lokad.AzureEventStore will fit your project comfortably if:
> * Your events are serialized with Json.NET, and weigh less than 512KB each.
> * Each aggregate receives less than 10 events per second.
> * The materialized views for all your aggregates fit in memory.

Are these recommendations due to Azure Blob Storage limits? Or from the way this library was built?

My project meets the first two bullet points. Regarding the third - my plan is to store the materialized views in an external store like Azure Tables or elasticsearch using [Azure Blob Storage's change feed.](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-change-feed) With this feature, I believe one could write a separate service ([e.g. Azure Function](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob)) that will consume the change feed and update one's projections. There's no need to keep the views in memory. I believe this library doesn't currently have this capability - I understand I'd have to build this myself. The change feed does have a significant limitation:

> Changes are written and made available in your change feed log within an order of a few minutes of the change.

However, for some scenarios this is acceptable.

(There are also ways to work around this - e.g. after appending an event to the blob, send a request (from the client code) to update the projections. The change feed will serve as a fallback for the 0.01% of requests that get lost to network nonsense, and projections should be idempoentent w/r/t receiving events. Alternatively, use [blob storage events](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-event-overview).)

**Comment by VictorNicollet** [comment]
The library is not restricted to small projects, but we choose to only recommend it for small projects. At Lokad, we are using this library in production with streams containing tens of gigabytes of data, and hundreds of millions of events, and we are fairly happy with it, but we do realize that not everyone may have the same expectations. 

Regarding the three limitations: 

 - JSON.NET + 512KB max-size is a fundamental design decision. We don't want to support huge events. 
 - Max 10 events/second for an aggregate: Azure Blob Storage does not respond very well above 10 writes/second. Right now the library performs one write for each call to `AppendEventsAsync()` but this is an implementation detail and we could detect high write loads and start batching writes, or offer this as a configuration option. 
 - Fit materialized views in memory: this is no longer really the case, and we have started using https://github.com/Lokad/LargeImmutable to deal with large materialized views by writing them to disk and then memory-mapping the result. Still, it requires a bit more work than just using `System.Collections.Immutable`. 

Your idea of storing the materialized views in an external store is possible, and the proper abstraction layer would be the `EventStream<TEvent>` (which is completely agnostic as to how the projections are materialized) rather than the `EventStreamService<TEvent, TState>` (which makes some strong assumptions about the projections being available in-memory). We do have a few internal projects that work at this abstraction level. 

However, be aware that you would be losing two strong consistency guarantees provided by the library, which are: 

 - `EventStreamService<TE, TS>.CurrentState()` always returns a projected view that takes into account _all_ events appended to the stream up to the moment the call was made. 
 - `EventStreamService<TE,TS>.AppendEventsAsync(callback)` always invokes the callback on the result of `CurrentState()`, and will repeatedly invoke the callback if it observes that new events have been appended by another machine/process/thread while the callback was running. 

If this level of consistency is not necessary for you (i.e. it is fine for readers and writers to see a stale version of the stream, so long as it's not stale beyond X milliseconds) then you can safely use `EventStream<TEvent>` as a read/write abstraction over a stream of JSON events stored in Azure Blob Storage.

**Comment by dharmaturtle** [comment]
Thank you very much for the fast and thorough answer!

**Comment by dharmaturtle** [comment]
It turns out Azure Append Blobs (which this library uses) [don't support the change feed](https://github.com/Azure/azure-sdk-for-net/issues/18353). As such, I'll likely write something that uses block blobs.

Side note, I see from [this feature request](https://feedback.azure.com/forums/217298-storage/suggestions/17678413-auto-defragment-append-blobs) that reading from the append blob has perf issues. What workaround, if any, have you arrived at?

**Comment by VictorNicollet** [comment]
The limitation happens for both the append blob and the block blob if blocks are too small. We work around it by re-packing the past append blobs into one large block blob, keeping the block size as large as possible. We call this compaction: https://github.com/Lokad/AzureEventStore/blob/master/Lokad.AzureEventStore/Drivers/AzureStorageDriver.cs#L502
