### ISSUE TITLE
Ordering in Projections

### ISSUE THREAD

**Issue by mcintyre321** [Lokad/AzureEventStore#2]
> Note that the projection should never rely on events being provided in any specific order. The library will routinely call the projection with the same event more than once, or with events that do not even appear in the event stream, or skip certain events entirely.
> 
> In a real-life project, this function would be implemented with a visitor pattern, but in the example project it is simply:
> 
>    public State Apply(uint sequence, IEvent e, State previous)
>    {
>            ...

Would it be reasonable to write this, if you want ordering?
    
   ```
uint next = 0;
   public State Apply(uint sequence, IEvent e, State previous)
   {
           if (sequence != next +1) return previous;
           next++;
           ...
```

**Comment by VictorNicollet** [comment]
In general, it is strongly recommended to not store any mutable state in the projections themselves - all state should be immutable and kept in the `State` type instead. 

Your example would likely fail if `Apply` is called on an event candidate at `sequence == next + 1`, and then that candidate was discarded because another application instance had already committed another event at `sequence == next + 1`. 

There is, however, a strong guarantee that the `State` passed to function `Apply` at `sequence == N` is the result of the call to `Apply` at `sequence == N - 1` (the state is built by applying events in chronological order).
